### ISSUE TITLE
[REQ] Please to set _NET_CURRENT_DESKTOP to 0 for workspace status

### ISSUE THREAD

**Issue by myugan** [tudurom/windowchef#43] opened 2018-02-03 20:53 UTC
I set my group number to 4.

I mean, when open new window not put on 0.
![2018-02-04-034525_352x72_scrot](https://user-images.githubusercontent.com/20453528/35771361-25be2c26-095e-11e8-9e7a-18f5dbc35c42.png)
The workspace status will be like : 
![2018-02-04-035031_377x38_scrot](https://user-images.githubusercontent.com/20453528/35771401-bd703b5e-095e-11e8-91cf-10aaebcf698c.png)

Then, if i move new window to workspace 1 and the output of xdotool like this.
![2018-02-04-034744_339x58_scrot](https://user-images.githubusercontent.com/20453528/35771373-5ca8f540-095e-11e8-8b9f-283f8cc8f4ef.png)
The workspace status will be like : 
![2018-02-04-034857_404x41_scrot](https://user-images.githubusercontent.com/20453528/35771393-8d74d0d6-095e-11e8-883b-cb618c2a7e1a.png)

Thanks.

**Comment by tudurom** [comment] 2018-02-14 09:24
I assume that you're using sticky windows. If that's correct, then I can't reproduce the issue. When I open a new window it will be assigned to the current workspace, which is by default the first.

**Closed as completed** 2019-01-03 18:43 UTC
